### ISSUE TITLE
2.0 release

### ISSUE THREAD

**Issue by skshetry** [iterative/dvc-objects#258]
```[tasklist]
### Tasks
- [ ] https://github.com/iterative/dvc-objects/pull/256
- [ ] https://github.com/iterative/dvc-objects/pull/257
- [x] Create `2.0` branch to merge breaking changes.
- [ ] Add support for scoped callbacks in fsspec
- [ ] Improve upstream `TqdmCallback`.
- [ ] Remove tqdm dependency and `TqdmCallback`.
```

**Comment by efiop** [comment]
We can take it lighter and jsut release a 2.0 right now and then release 3.0, no one is holding us down. Sounds like scoped callbacks will take awhile to propagate/release.

**Comment by skshetry** [comment]
Okay, let's make a 3.0 release then.
