### ISSUE TITLE
4.0 release

### ISSUE THREAD

**Issue by skshetry** [iterative/dvc-objects#272]
```[tasklist]
### Tasks
- [x] Bump minver of `fsspec` to `2024.2.0`
- [x] Remove `dvc_objects.fs.Callback` and subclasses.
- [x] Remove/rework `TqdmCallback`.
- [x] Get rid of `wrap_fn`/`branch_callback`/`wrap_and_branch_callback` if possible.
- [x] Remove `dvc_objects._tqdm` if possible.
```

Also see https://github.com/iterative/dvc-objects/issues/258.

**Comment by skshetry** [comment]
https://github.com/iterative/dvc-azure/issues/76 should happen before the 4.0 release. 
DVC should bump dvc-objects and dvc-azure at the same time.

**Comment by skshetry** [comment]
Done in #279.
